version: '2'

services:
    nginx:
        ports:
            - "8080:80"
    fpm:
        volumes:
            - "./:/var/www/html"
    rabbit:
        ports:
            - "15672:15672"

    toolbox:
        volumes_from:
            - "fpm"
        networks:
            - main

        image: "coffeelovers/php:7.0-toolbox"
