FROM php:7.0

WORKDIR /usr/local/bin
RUN curl -o composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php \
    && ln -s composer.phar composer

RUN apt-get update && apt-get -y install git
RUN docker-php-ext-install bcmath

COPY fpm/xdebug.so /usr/local/lib/php/extensions/no-debug-non-zts-20151012/
COPY fpm/php.ini /usr/local/etc/php/

WORKDIR /var/www/html
